title: Over Da Rainbow
description: Profiles, Projects, and Interests for the UH Community
google_analytics:
show_downloads: false
theme: jekyll-theme-tactile
github:
  is_project_page: true
  repository_url: https://github.com/over-da-rainbow/over-da-rainbow
gems:
  - jekyll-mentions
